### ISSUE TITLE
[Ontology] changeRequest: information for temperature-sensitive goods (minTemperature, maxTemperature, temperatureUnit)

### ISSUE THREAD

**Issue by LauraWeissgerber** [IATA-Cargo/ONE-Record#170]
I am not sure where to put the information regarding temperature sensitive goods like: minimum temperature, maximum temperature, temperature unit.

In my opinion this information could be in BookingOptionRequest - shipment - handlingInstructions.

Would this be a Special Service Request (SSR) OR Other Service Information (OSI)?

My proposal is to add a new object "temperature-sensitive" in "handlingInstructions".

temperatureSensitive:
minTemperature: value
maxTemperature: value

**Comment by mskopp** [comment]
My gut feeling is that is should better go to ServiceRequest instead to HandlingInstructions, but the problem about missing details on either SR or HI remains.
I think this should be reviewed in a wider range since Special Care requirements do not limit to temperatures.. the topic of Care Protocols is already covered by a ongoing initiative of CargoIQ. Maybe makes sense to team up with them.

**Comment by lambertciata** [comment]
Hi,
With regards to Care Protocol approach, my understanding is that CargoiQ applies a certain Care Package based on goods description and Special Handling Codes defined.
I recall a discussion on having a Temperature range being defined as part of handling instructions, following the principles of a Min and Max Temperature as well as using Special Handling Codes with temperatures ranges defined in the TCR (Temperature Control Regulation).
On SPH side we have Frozen (FRO), Control Room +15/+25 (CRT) and Extended Room +2/+25.
I suggest to discuss the topic with the taskforce and come up with a proposal.

**Comment by lambertciata** [comment]
closed with 3.0.0
