### ISSUE TITLE
[Data Model] Update data that is not a LO

### ISSUE THREAD

**Issue by grichka** [IATA-Cargo/ONE-Record#94]
The ONE Record API and Security specification describes how to update a LO.
But how should a ONE Record server is supposed to handle updates of Company address for example? 
How to notify other parties that data has changed?

What about reference data like Country or Location? How to update them and who should host them?

**Comment by andrablaj** [comment]
As discussed in the latest ONE Record API & Security Working Group call, in order to update data that is not a LO, a PATCH request should be sent on the LO containing the data to be updated. If these nested objects have their own "updating cycle" as they may be reference objects, then they might need to be separated into standalone Logistics Objects. To be discussed in the ONE Record Data Model Working Group.

**Comment by lambertciata** [comment]
I think the issue has been clarified, if there is more to assess please let us know and we'll open again.
